/**
 * Regenerates the emoji pack shipped from `@taiga-ui/experimental/emoji`.
 *
 * The pack is plain data with no dependency on any component: `tui-icon-list`
 * projects whatever you render, so it never sees this shape.
 *
 * Run manually after a Unicode release, commit the result:
 *   npx ts-node ./scripts/generate-emoji.ts
 *
 * The output is vendored rather than generated at build time on purpose — the
 * build must not depend on the network.
 *
 * Sources (both under the permissive Unicode license):
 *  - emoji-test.txt      canonical order, groups and names
 *  - CLDR annotations    search keywords, English only
 */
import {writeFileSync} from 'node:fs';
import {join} from 'node:path';

const EMOJI_TEST = 'https://unicode.org/Public/emoji/latest/emoji-test.txt';
const ANNOTATIONS =
    'https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotations/en.xml';

const OUTPUT = join('projects', 'experimental', 'emoji', 'emoji.ts');

/**
 * Unicode top level groups mapped onto Taiga icons for the category tabs.
 * Groups absent from this map are dropped — `Component` holds modifiers that
 * are not standalone emoji.
 */
const GROUPS: Record<string, string> = {
    'Smileys & Emotion': '@tui.smile',
    'People & Body': '@tui.smile',
    'Animals & Nature': '@tui.cat',
    'Food & Drink': '@tui.hamburger',
    'Travel & Places': '@tui.bus',
    Activities: '@tui.trophy',
    Objects: '@tui.lightbulb',
    Symbols: '@tui.music',
    Flags: '@tui.flag',
};

/**
 * Fitzpatrick skin tone modifiers. An emoji carrying one is not a separate
 * entry — it is a variant of the same emoji with the modifier stripped.
 */
const TONES = /[\u{1F3FB}-\u{1F3FF}]/gu;

interface Entry {
    value: string;
    name: string;
    group: string;
    tags: string[];
    variants: Array<{value: string; name: string}>;
}

void main();

async function main(): Promise<void> {
    const [test, annotations] = await Promise.all([
        fetchText(EMOJI_TEST),
        fetchText(ANNOTATIONS),
    ]);
    const keywords = parseAnnotations(annotations);
    const entries = parseEmojiTest(test, keywords);

    writeFileSync(OUTPUT, print(entries));

    const count = entries.reduce((total, {items}) => total + items.length, 0);

    console.info(`${OUTPUT}: ${entries.length} groups, ${count} emoji`);
}

async function fetchText(url: string): Promise<string> {
    const response = await fetch(url);

    if (!response.ok) {
        throw new Error(`${url} responded ${response.status}`);
    }

    return response.text();
}

function parseAnnotations(xml: string): Map<string, string[]> {
    const result = new Map<string, string[]>();
    const pattern = /<annotation cp="([^"]+)">([^<]+)<\/annotation>/g;

    for (const [, cp = '', list = ''] of xml.matchAll(pattern)) {
        result.set(
            cp,
            list.split('|').map((keyword) => decode(keyword.trim())),
        );
    }

    return result;
}

function parseEmojiTest(
    text: string,
    keywords: Map<string, string[]>,
): Array<{label: string; icon: string; items: Entry[]}> {
    const groups = new Map<string, Map<string, Entry>>();
    let group = '';

    for (const line of text.split('\n')) {
        const header = /^# group: (.+)$/.exec(line.trim());

        if (header?.[1]) {
            group = header[1];
            continue;
        }

        // 1F600 ; fully-qualified # 😀 E1.0 grinning face
        const match =
            /^([0-9A-F ]+);\s+fully-qualified\s+#\s+(\S+)\s+E[\d.]+\s+(.+)$/.exec(line);
        const icon = GROUPS[group];

        if (!match || !icon) {
            continue;
        }

        const [, , value = '', name = ''] = match;
        const base = value.replaceAll(TONES, '');
        const label = group === 'People & Body' ? 'Smileys & Emotion' : group;
        const items = groups.get(label) ?? new Map<string, Entry>();

        groups.set(label, items);

        if (base === value) {
            items.set(value, {
                value,
                name,
                group: label,
                tags: keywords.get(value) ?? [],
                variants: [],
            });
        } else {
            // Skin tone: attach to the base emoji instead of listing it inline
            items.get(base)?.variants.push({value, name});
        }
    }

    return [...groups].map(([label, items]) => ({
        label,
        icon: GROUPS[label] ?? '',
        items: [...items.values()],
    }));
}

function print(groups: Array<{label: string; icon: string; items: Entry[]}>): string {
    const body = groups
        .map(
            ({label, icon, items}) => `    {
        label: ${quote(label)},
        icon: ${quote(icon)},
        items: [
${items.map(printItem).join('\n')}
        ],
    },`,
        )
        .join('\n');

    return `/**
 * GENERATED by scripts/generate-emoji.ts — do not edit by hand.
 *
 * Data derived from Unicode CLDR, distributed under the Unicode license.
 */
export interface TuiEmoji {
    readonly value: string;
    readonly name: string;
    readonly tags?: readonly string[];
    /** Skin tone variants of the same emoji, base first. */
    readonly variants?: readonly TuiEmoji[];
}

export interface TuiEmojiGroup {
    readonly label: string;
    readonly icon: string;
    readonly items: readonly TuiEmoji[];
}

export const TUI_EMOJI: readonly TuiEmojiGroup[] = [
${body}
];
`;
}

function printItem({value, name, tags, variants}: Entry): string {
    const parts = [`value: ${quote(value)}`, `name: ${quote(name)}`];

    if (tags.length) {
        parts.push(`tags: [${tags.map(quote).join(', ')}]`);
    }

    if (variants.length) {
        parts.push(
            `variants: [${variants
                .map(({value, name}) => `{value: ${quote(value)}, name: ${quote(name)}}`)
                .join(', ')}]`,
        );
    }

    return `            {${parts.join(', ')}},`;
}

function quote(value: string): string {
    return `'${value.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)}'`;
}

function decode(value: string): string {
    return value
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&apos;', "'");
}
